title: Jermaine Varnicker # your name (or website title) here

logo: "images/Jermaine git Photo.jpg?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="https://www.linkedin.com/in/jermaine-varnicker-315a8794/">View My LinkedIn Profile</a> 
  <a href="https://www.linkedin.com/in/jermaine-varnicker-315a8794/">View My LinkedIn Profile</a> 
  <a href="https://github.com/JermaineV">GitHub</a>  Welcome to My Data Science Portfolio
  <br><br>
  This Portfolio is a compilation of all the Data Science and Data Analysis projects I have done for academic, self-learning and hobby purposes. This portfolio is updated on the regular basis 
  <br><br>
  
theme: jekyll-theme-minimal
