title: <p align="center"> Jermaine Varnicker </p>

logo: img class="circular--square"images/Jermaine git Photo.jpg"

description:
  <p align="center">
  <a href="pdf/Resume-Jvarnicker-varnicker (1).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jermaine-varnicker-315a8794/">LinkedIn</a> |
  <a href="https://github.com/JermaineV">GitHub</a>  
  </p>
  
  <p align="justify">
  Welcome to My Data Science Portfolio
  <br><br>
  This Portfolio is a compilation of all the Data Science and Data Analysis projects I have done for academic, self-learning and hobby purposes. 
  <br><br>
  </p>
  
  
theme: jekyll-theme-minimal
