title: <p align="center"> Jermaine Varnicker </p>

logo: "images/IMG_20210715_231741.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/Resume-Jvarnicker-varnicker (1).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jermaine-varnicker-315a8794/">LinkedIn</a> |
  <a href="https://github.com/JermaineV">GitHub</a>  
  </p>
  
  <p align="justify">
  Welcome to My Data Science Portfolio
  <br><br>
  
  ABOUT ME
  <br><br>

  I enjoy playing chess, online gaming and just having fun.
  
  Before entering the field of data science, I studied Mechatronic Engineering at the University of South Africa but I was unable to complete my degree after falling on some difficult times. 
  Later I was presented with the opportunity to study data science and having already had a background in programming thanks to my engineering studies I was able to perform exaptational well as a student in the field.
  I am also a Certified Mcrosoft T-SQL programmer, below is a link to my accretied badge.
  
  <div data-iframe-width="150" data-iframe-height="270" data-share-badge-id="b509cdcd-1d97-4ab1-8220-4e6a40f17179" data-share-badge-host="https://www.credly.com"></div><script type="text/javascript" async src="//cdn.credly.com/assets/utilities/embed.js"></script>
  
theme: jekyll-theme-minimal
