title: <p align="center"> Jermaine Varnicker </p>

logo: "images/IMG_20210715_231741.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/Resume-Jermaine-varnicker (1).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jermaine-varnicker-315a8794/">LinkedIn</a> |
  <a href="https://github.com/JermaineV">GitHub</a>  | 
  <a href="mailto:jvarnicker@gmail.com">Email</a>
  </p>
  
  <p>
  Data scientist, Programmer, Developer, and a lover of all things tech. 
  <br><br>
  





  </p>

  <div data-iframe-width="150" data-iframe-height="270" data-share-badge-id="b509cdcd-1d97-4ab1-8220-4e6a40f17179" data-share-badge-host="https://www.credly.com"></div><script type="text/javascript" async src="//cdn.credly.com/assets/utilities/embed.js"></script>

theme: jekyll-theme-minimal
