title: "<p align='center'>Jermaine Varnicker</p>"
logo: "images/IMG_20210715_231741.jpg?raw=true"
---
description: |
  Data scientist, AI/ML Engineer, Developer, and a lover of all things tech. |
---
  <p align="center">
    <a href="pdf/Jermaine resume24.pdf">Resume</a> |
    <a href="pdf/transcripts - Jermaine Varnicker.pdf">Academic Transcript</a> |
    <a href="https://www.linkedin.com/in/jermaine-varnicker-315a8794/">LinkedIn</a> |
    <a href="https://github.com/JermaineV">GitHub</a> |
    <a href="mailto:jvarnicker@gmail.com">Email</a>
  </p>
---
theme: jekyll-theme-minimal
