title: <p align="center"> Jermaine Varnicker
logo: "images/IMG_20210715_231741.jpg?raw=true" 


description:
   Data scientist, Programmer, Developer, and a lover of all things tech.
  <div data-iframe-width="280" data-iframe-height="230" data-share-badge-id="b509cdcd-1d97-4ab1-8220-4e6a40f17179" data-share-badge-host="https://www.credly.com"></div><script type="text/javascript" async src="//cdn.credly.com/assets/utilities/embed.js"></script>
  <p align="center">

  <a href="pdf/Jermaine resume 2022.pdf">Resume</a> |
  <a href="pdf/pdfjoiner (1).pdf">Academic Transcript </a> |
  <a href="https://www.linkedin.com/in/jermaine-varnicker-315a8794/">LinkedIn</a> |
  <a href="https://github.com/JermaineV">GitHub</a> | 
  <a href="mailto:jvarnicker@gmail.com">Email</a>
 

theme: jekyll-theme-minimal
